version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
    entrypoint: ["python", "app.py"]
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: meteoapi
      POSTGRES_USER: meteoapi
      POSTGRES_PASSWORD: meteoapi123
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

